/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * About.java
 *
 * Created on 03 19, 19, 7:56:03 PM
 */
package loginform;
import javax.swing.JOptionPane;
public class About extends javax.swing.JFrame {

    /** Creates new form About */
    public About() {
        initComponents();
        setLocationRelativeTo(null);
        BRIOL.setVisible(false);
        KC.setVisible(false);
        RUBIEL.setVisible(false);
        PADILLA.setVisible(false);
        JESUS.setVisible(false);
                BRIOL.setVisible(false);
        KC.setVisible(false);
        RUBIEL.setVisible(false);
        PADILLA.setVisible(false);
        JESUS.setVisible(false);
        padi.setVisible(false);
        verso.setVisible(false);
        dela.setVisible(false);
        brio.setVisible(false);
        loza.setVisible(false);
        aboutjasmine.setVisible(false);
                aboutjesus.setVisible(false);
                        aboutkc.setVisible(false);
                                aboutrubiel.setVisible(false);
                                        aboutregine.setVisible(false);
                                        back1.setVisible(false);
                                        back2.setVisible(false);
                                        back3.setVisible(false);
                                        back4.setVisible(false);
                                        back5.setVisible(false);

        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back5 = new javax.swing.JLabel();
        back4 = new javax.swing.JLabel();
        back3 = new javax.swing.JLabel();
        back1 = new javax.swing.JLabel();
        back2 = new javax.swing.JLabel();
        leib = new javax.swing.JButton();
        ck = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        briol1 = new javax.swing.JButton();
        jjesus = new javax.swing.JButton();
        jas = new javax.swing.JButton();
        padi = new javax.swing.JLabel();
        brio = new javax.swing.JLabel();
        loza = new javax.swing.JLabel();
        dela = new javax.swing.JLabel();
        aboutjasmine = new javax.swing.JLabel();
        aboutregine = new javax.swing.JLabel();
        aboutjesus = new javax.swing.JLabel();
        aboutrubiel = new javax.swing.JLabel();
        aboutkc = new javax.swing.JLabel();
        verso = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        RUBIEL = new javax.swing.JLabel();
        BRIOL = new javax.swing.JLabel();
        KC = new javax.swing.JLabel();
        JESUS = new javax.swing.JLabel();
        PADILLA = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        coffin5 = new javax.swing.JLabel();
        coffin4 = new javax.swing.JLabel();
        coffin2 = new javax.swing.JLabel();
        coffin3 = new javax.swing.JLabel();
        coffin1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1441, 662));
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        back5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        back5.setForeground(new java.awt.Color(255, 51, 51));
        back5.setText("X");
        back5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back5MouseClicked(evt);
            }
        });
        getContentPane().add(back5);
        back5.setBounds(1180, 180, 33, 70);

        back4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        back4.setForeground(new java.awt.Color(255, 51, 51));
        back4.setText("X");
        back4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back4MouseClicked(evt);
            }
        });
        getContentPane().add(back4);
        back4.setBounds(890, 180, 33, 70);

        back3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        back3.setForeground(new java.awt.Color(255, 51, 51));
        back3.setText("X");
        back3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back3MouseClicked(evt);
            }
        });
        getContentPane().add(back3);
        back3.setBounds(600, 180, 33, 70);

        back1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        back1.setForeground(new java.awt.Color(255, 51, 51));
        back1.setText("X");
        back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back1MouseClicked(evt);
            }
        });
        getContentPane().add(back1);
        back1.setBounds(40, 180, 33, 70);

        back2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        back2.setForeground(new java.awt.Color(255, 51, 51));
        back2.setText("X");
        back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back2MouseClicked(evt);
            }
        });
        getContentPane().add(back2);
        back2.setBounds(330, 180, 33, 70);

        leib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/franksilebi.png"))); // NOI18N
        leib.setBorderPainted(false);
        leib.setContentAreaFilled(false);
        leib.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/DIG.png"))); // NOI18N
        leib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leibMouseClicked(evt);
            }
        });
        getContentPane().add(leib);
        leib.setBounds(620, 340, 220, 190);

        ck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/ck.png"))); // NOI18N
        ck.setBorderPainted(false);
        ck.setContentAreaFilled(false);
        ck.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/DIG.png"))); // NOI18N
        ck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckMouseClicked(evt);
            }
        });
        getContentPane().add(ck);
        ck.setBounds(330, 340, 220, 190);

        jButton9.setBackground(new java.awt.Color(0, 102, 153));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton9.setText("X");
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(1370, 0, 70, 50);

        briol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/kalabasimare.png"))); // NOI18N
        briol1.setBorderPainted(false);
        briol1.setContentAreaFilled(false);
        briol1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/DIG.png"))); // NOI18N
        briol1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                briol1MouseClicked(evt);
            }
        });
        getContentPane().add(briol1);
        briol1.setBounds(50, 360, 220, 150);

        jjesus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/zombiako.png"))); // NOI18N
        jjesus.setBorderPainted(false);
        jjesus.setContentAreaFilled(false);
        jjesus.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/DIG.png"))); // NOI18N
        jjesus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jjesusMouseClicked(evt);
            }
        });
        getContentPane().add(jjesus);
        jjesus.setBounds(880, 330, 230, 210);

        jas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/witchsijas.png"))); // NOI18N
        jas.setBorderPainted(false);
        jas.setContentAreaFilled(false);
        jas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/DIG.png"))); // NOI18N
        jas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jasMouseClicked(evt);
            }
        });
        getContentPane().add(jas);
        jas.setBounds(1210, 350, 150, 170);

        padi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/padi.png"))); // NOI18N
        getContentPane().add(padi);
        padi.setBounds(1220, 500, 130, 70);

        brio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/BRIO.png"))); // NOI18N
        getContentPane().add(brio);
        brio.setBounds(80, 510, 150, 70);

        loza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/LOZA.png"))); // NOI18N
        getContentPane().add(loza);
        loza.setBounds(360, 510, 150, 70);

        dela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/DELA.png"))); // NOI18N
        getContentPane().add(dela);
        dela.setBounds(650, 510, 150, 60);

        aboutjasmine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/aboutjasmine.png"))); // NOI18N
        getContentPane().add(aboutjasmine);
        aboutjasmine.setBounds(1150, 170, 290, 420);

        aboutregine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/aboutregine.png"))); // NOI18N
        getContentPane().add(aboutregine);
        aboutregine.setBounds(10, 170, 280, 430);

        aboutjesus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/aboutjesus.png"))); // NOI18N
        getContentPane().add(aboutjesus);
        aboutjesus.setBounds(860, 160, 310, 440);

        aboutrubiel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/aboutrubiel.png"))); // NOI18N
        getContentPane().add(aboutrubiel);
        aboutrubiel.setBounds(580, 170, 290, 420);

        aboutkc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/aboutkc.png"))); // NOI18N
        getContentPane().add(aboutkc);
        aboutkc.setBounds(300, 170, 280, 430);

        verso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/verso.png"))); // NOI18N
        getContentPane().add(verso);
        verso.setBounds(930, 500, 130, 70);

        back.setFont(new java.awt.Font("Tw Cen MT", 1, 18));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/back.png"))); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setFocusPainted(false);
        back.setFocusable(false);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(20, 10, 110, 50);

        RUBIEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/RUBIEL.png"))); // NOI18N
        RUBIEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RUBIELMouseClicked(evt);
            }
        });
        getContentPane().add(RUBIEL);
        RUBIEL.setBounds(660, 370, 130, 140);

        BRIOL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/BRIOL.png"))); // NOI18N
        BRIOL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BRIOLMouseClicked(evt);
            }
        });
        getContentPane().add(BRIOL);
        BRIOL.setBounds(100, 370, 160, 140);

        KC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/KC.png"))); // NOI18N
        KC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KCMouseClicked(evt);
            }
        });
        getContentPane().add(KC);
        KC.setBounds(370, 360, 140, 150);

        JESUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/JESUS.png"))); // NOI18N
        JESUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JESUSMouseClicked(evt);
            }
        });
        getContentPane().add(JESUS);
        JESUS.setBounds(930, 360, 140, 150);

        PADILLA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/PADILLA.png"))); // NOI18N
        PADILLA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PADILLAMouseClicked(evt);
            }
        });
        getContentPane().add(PADILLA);
        PADILLA.setBounds(1210, 350, 160, 160);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/mare.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 500, 1420, 160);

        coffin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/lebeng.png"))); // NOI18N
        coffin5.setText("\\");
            getContentPane().add(coffin5);
            coffin5.setBounds(1130, 160, 290, 530);

            coffin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/lebeng.png"))); // NOI18N
            coffin4.setText("\\");
                getContentPane().add(coffin4);
                coffin4.setBounds(850, 170, 290, 530);

                coffin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/lebeng.png"))); // NOI18N
                coffin2.setText("\\");
                    getContentPane().add(coffin2);
                    coffin2.setBounds(290, 180, 290, 530);

                    coffin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/lebeng.png"))); // NOI18N
                    coffin3.setText("\\");
                        getContentPane().add(coffin3);
                        coffin3.setBounds(580, 170, 290, 530);

                        coffin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/lebeng.png"))); // NOI18N
                        coffin1.setText("\\");
                            getContentPane().add(coffin1);
                            coffin1.setBounds(10, 180, 290, 530);

                            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/ab.png"))); // NOI18N
                            getContentPane().add(jLabel3);
                            jLabel3.setBounds(180, -10, 1110, 180);

                            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/nightforscare.png"))); // NOI18N
                            getContentPane().add(jLabel2);
                            jLabel2.setBounds(0, -20, 1440, 170);

                            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/cemetolit.png"))); // NOI18N
                            getContentPane().add(jLabel1);
                            jLabel1.setBounds(0, 150, 1440, 510);
                            getContentPane().add(jPanel1);
                            jPanel1.setBounds(20, 160, 280, 420);

                            pack();
                        }// </editor-fold>//GEN-END:initComponents

private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked


}//GEN-LAST:event_backMouseClicked

private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
dispose();
new Home().setVisible(true);
}//GEN-LAST:event_backActionPerformed

private void jasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jasMouseClicked
padi.setVisible(true);
jas.setVisible(false);
PADILLA.setVisible(true);
verso.setVisible(false);
jjesus.setVisible(true);
JESUS.setVisible(false);
dela.setVisible(false);
leib.setVisible(true);
RUBIEL.setVisible(false);
brio.setVisible(false);
briol1.setVisible(true);
BRIOL.setVisible(false);
KC.setVisible(false);
ck.setVisible(true);
verso.setVisible(false);
loza.setVisible(false);
}//GEN-LAST:event_jasMouseClicked

private void jjesusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jjesusMouseClicked
verso.setVisible(true);
jjesus.setVisible(false);
JESUS.setVisible(true);
dela.setVisible(false);
leib.setVisible(true);
RUBIEL.setVisible(false);
brio.setVisible(false);
briol1.setVisible(true);
BRIOL.setVisible(false);
KC.setVisible(false);
ck.setVisible(true);
loza.setVisible(false);
padi.setVisible(false);
jas.setVisible(true);
PADILLA.setVisible(false);
verso.setVisible(false);
}//GEN-LAST:event_jjesusMouseClicked

private void leibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leibMouseClicked
dela.setVisible(true);
leib.setVisible(false);
RUBIEL.setVisible(true);
brio.setVisible(false);
briol1.setVisible(true);
BRIOL.setVisible(false);
KC.setVisible(false);
ck.setVisible(true);
loza.setVisible(false);
verso.setVisible(false);
jjesus.setVisible(true);
JESUS.setVisible(false);
padi.setVisible(false);
jas.setVisible(true);
PADILLA.setVisible(false);
verso.setVisible(false);
}//GEN-LAST:event_leibMouseClicked

private void briol1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_briol1MouseClicked
brio.setVisible(true);
briol1.setVisible(false);
BRIOL.setVisible(true);
dela.setVisible(false);
leib.setVisible(true);
RUBIEL.setVisible(false);
KC.setVisible(false);
ck.setVisible(true);
loza.setVisible(false);
jjesus.setVisible(true);
JESUS.setVisible(false);
padi.setVisible(false);
jas.setVisible(true);
PADILLA.setVisible(false);
verso.setVisible(false);

}//GEN-LAST:event_briol1MouseClicked

private void ckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckMouseClicked
KC.setVisible(true);
ck.setVisible(false);
loza.setVisible(true);
brio.setVisible(false);
briol1.setVisible(true);
BRIOL.setVisible(false);
dela.setVisible(false);
leib.setVisible(true);
RUBIEL.setVisible(false);
jjesus.setVisible(true);
verso.setVisible(false);
JESUS.setVisible(false);
padi.setVisible(false);
jas.setVisible(true);
PADILLA.setVisible(false);

}//GEN-LAST:event_ckMouseClicked

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
int YesorNO =JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?","Exit",JOptionPane.YES_NO_OPTION);
if(YesorNO==0){
    System.exit(0);
}
        // TODO add your handling code here:
}//GEN-LAST:event_jButton9ActionPerformed

private void RUBIELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RUBIELMouseClicked
  coffin3.setVisible(false);
 RUBIEL.setVisible(false);
  leib.setVisible(false);
dela.setVisible(false);
 aboutrubiel.setVisible(true);
 brio.setVisible(false);
  BRIOL.setVisible(false);
  briol1.setVisible(false);
  KC.setVisible(false);
ck.setVisible(false);
loza.setVisible(false);
jjesus.setVisible(false);
JESUS.setVisible(false);
verso.setVisible(false);
PADILLA.setVisible(false);
jas.setVisible(false);
padi.setVisible(false);
back3.setVisible(true);
}//GEN-LAST:event_RUBIELMouseClicked

private void BRIOLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BRIOLMouseClicked
 coffin1.setVisible(false);
  brio.setVisible(false);
  BRIOL.setVisible(false);
  briol1.setVisible(false);
  aboutregine.setVisible(true);
  RUBIEL.setVisible(false);
  leib.setVisible(false);
 dela.setVisible(false);
 KC.setVisible(false);
ck.setVisible(false);
loza.setVisible(false);
jjesus.setVisible(false);
JESUS.setVisible(false);
verso.setVisible(false);
PADILLA.setVisible(false);
jas.setVisible(false);
padi.setVisible(false);
back1.setVisible(true);
}//GEN-LAST:event_BRIOLMouseClicked

private void KCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KCMouseClicked
KC.setVisible(false);
ck.setVisible(false);
loza.setVisible(false);
coffin2.setVisible(false);
aboutkc.setVisible(true);
 RUBIEL.setVisible(false);
  leib.setVisible(false);
dela.setVisible(false);
 brio.setVisible(false);
  BRIOL.setVisible(false);
  briol1.setVisible(false);
  jjesus.setVisible(false);
JESUS.setVisible(false);
verso.setVisible(false);
PADILLA.setVisible(false);
jas.setVisible(false);
padi.setVisible(false);
back2.setVisible(true);
}//GEN-LAST:event_KCMouseClicked

private void JESUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JESUSMouseClicked
coffin4.setVisible(false);
jjesus.setVisible(false);
JESUS.setVisible(false);
verso.setVisible(false);
 aboutjesus.setVisible(true);
RUBIEL.setVisible(false);
  leib.setVisible(false);
dela.setVisible(false);
 brio.setVisible(false);
  BRIOL.setVisible(false);
  briol1.setVisible(false);
  KC.setVisible(false);
ck.setVisible(false);
loza.setVisible(false);
PADILLA.setVisible(false);
jas.setVisible(false);
padi.setVisible(false);
back4.setVisible(true);
}//GEN-LAST:event_JESUSMouseClicked

private void PADILLAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PADILLAMouseClicked
  coffin5.setVisible(false);
PADILLA.setVisible(false);
jas.setVisible(false);
padi.setVisible(false);
 aboutjasmine.setVisible(true);
jjesus.setVisible(false);
JESUS.setVisible(false);
verso.setVisible(false);
RUBIEL.setVisible(false);
  leib.setVisible(false);
dela.setVisible(false);
 brio.setVisible(false);
  BRIOL.setVisible(false);
  briol1.setVisible(false);
  KC.setVisible(false);
  back5.setVisible(true);
ck.setVisible(false);
}//GEN-LAST:event_PADILLAMouseClicked

private void back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseClicked
coffin1.setVisible(true);
  briol1.setVisible(true);
  aboutregine.setVisible(false);
  back1.setVisible(false);
  ck.setVisible(true);
          leib .setVisible(true);
          jjesus.setVisible(true);
          jas.setVisible(true);
}//GEN-LAST:event_back1MouseClicked

private void back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2MouseClicked
back2.setVisible(false);
KC.setVisible(false);
ck.setVisible(true);
loza.setVisible(false);
coffin2.setVisible(true);
aboutkc.setVisible(false);
  leib .setVisible(true);
          jjesus.setVisible(true);
          jas.setVisible(true);
          briol1.setVisible(true);
}//GEN-LAST:event_back2MouseClicked

private void back3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back3MouseClicked
 coffin3.setVisible(true);
 RUBIEL.setVisible(false);
  leib.setVisible(true);
dela.setVisible(false);
 aboutrubiel.setVisible(false);
   jjesus.setVisible(true);
          jas.setVisible(true);
          briol1.setVisible(true);
       
 back3.setVisible(false);
 ck.setVisible(true);

}//GEN-LAST:event_back3MouseClicked

private void back4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back4MouseClicked
  coffin4.setVisible(true);
jjesus.setVisible(true);
JESUS.setVisible(false);
verso.setVisible(false);
 aboutjesus.setVisible(false);
 back4.setVisible(false);
  jas.setVisible(true);
          briol1.setVisible(true);
         leib.setVisible(true);
          ck.setVisible(true);
}//GEN-LAST:event_back4MouseClicked

private void back5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back5MouseClicked
back5.setVisible(false);
coffin5.setVisible(true);
PADILLA.setVisible(false);
jas.setVisible(true);
padi.setVisible(false);
 aboutjasmine.setVisible(false);
   briol1.setVisible(true);
         leib.setVisible(true);
          ck.setVisible(true);
          jjesus.setVisible(true);
}//GEN-LAST:event_back5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new About().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BRIOL;
    private javax.swing.JLabel JESUS;
    private javax.swing.JLabel KC;
    private javax.swing.JLabel PADILLA;
    private javax.swing.JLabel RUBIEL;
    private javax.swing.JLabel aboutjasmine;
    private javax.swing.JLabel aboutjesus;
    private javax.swing.JLabel aboutkc;
    private javax.swing.JLabel aboutregine;
    private javax.swing.JLabel aboutrubiel;
    private javax.swing.JButton back;
    private javax.swing.JLabel back1;
    private javax.swing.JLabel back2;
    private javax.swing.JLabel back3;
    private javax.swing.JLabel back4;
    private javax.swing.JLabel back5;
    private javax.swing.JLabel brio;
    private javax.swing.JButton briol1;
    private javax.swing.JButton ck;
    private javax.swing.JLabel coffin1;
    private javax.swing.JLabel coffin2;
    private javax.swing.JLabel coffin3;
    private javax.swing.JLabel coffin4;
    private javax.swing.JLabel coffin5;
    private javax.swing.JLabel dela;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jas;
    private javax.swing.JButton jjesus;
    private javax.swing.JButton leib;
    private javax.swing.JLabel loza;
    private javax.swing.JLabel padi;
    private javax.swing.JLabel verso;
    // End of variables declaration//GEN-END:variables
}
