/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Housetype.java
 *
 * Created on May 8, 2023, 8:44:35 AM
 */

package loginform;



import javax.swing.JOptionPane;
public class Housetype extends javax.swing.JFrame {

 
    public Housetype() {
        initComponents();
        setLocationRelativeTo(null);
        housetype.setVisible(false);
        spine.setVisible(true);
        buthus.setVisible(true);
    panpan.setVisible(false);
    mario.setVisible(false);
    pan1.setVisible(false);
    marionette.setVisible(false);
    skintaker.setVisible(false);
    mansion.setVisible(false);
    noend.setVisible(false);
    nightmarecove.setVisible(false);
    backbut.setVisible(false);
    no.setVisible(false);
    skin.setVisible(false);
    night.setVisible(false);
    slau.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        panpan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backbut = new javax.swing.JButton();
        noend = new javax.swing.JLabel();
        marionette = new javax.swing.JLabel();
        nightmarecove = new javax.swing.JLabel();
        skintaker = new javax.swing.JLabel();
        spine = new javax.swing.JLabel();
        housetype = new javax.swing.JLabel();
        mansion = new javax.swing.JLabel();
        buthus = new javax.swing.JButton();
        mario = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        night = new javax.swing.JLabel();
        skin = new javax.swing.JLabel();
        slau = new javax.swing.JLabel();
        pan1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setFocusableWindowState(false);
        setMinimumSize(new java.awt.Dimension(1358, 702));
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        back.setFont(new java.awt.Font("Tw Cen MT", 1, 18));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/back.png"))); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setFocusPainted(false);
        back.setFocusable(false);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(20, 10, 110, 50);

        jButton9.setBackground(new java.awt.Color(0, 102, 153));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 48));
        jButton9.setForeground(new java.awt.Color(255, 0, 0));
        jButton9.setText("X");
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(1300, 0, 70, 50);

        panpan.setBackground(new java.awt.Color(0, 0, 0));
        panpan.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/nigggg.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panpan.add(jLabel5);
        jLabel5.setBounds(10, 250, 460, 200);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/skin.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        panpan.add(jLabel6);
        jLabel6.setBounds(830, 220, 470, 270);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/mar.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panpan.add(jLabel3);
        jLabel3.setBounds(0, -20, 530, 170);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/noend2.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panpan.add(jLabel4);
        jLabel4.setBounds(820, 0, 470, 150);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/slagg.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panpan.add(jLabel7);
        jLabel7.setBounds(370, 90, 590, 210);

        getContentPane().add(panpan);
        panpan.setBounds(40, 140, 1290, 440);

        backbut.setText("Back");
        backbut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbut.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        backbut.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        backbut.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/close (1).png"))); // NOI18N
        backbut.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        backbut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        backbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbutMouseClicked(evt);
            }
        });
        backbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutActionPerformed(evt);
            }
        });
        getContentPane().add(backbut);
        backbut.setBounds(20, 650, 110, 40);

        noend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/noind.png"))); // NOI18N
        getContentPane().add(noend);
        noend.setBounds(220, 190, 1110, 390);

        marionette.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/marion.png"))); // NOI18N
        getContentPane().add(marionette);
        marionette.setBounds(220, 180, 980, 420);

        nightmarecove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/nightmor.png"))); // NOI18N
        getContentPane().add(nightmarecove);
        nightmarecove.setBounds(220, 180, 990, 410);

        skintaker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/skint.png"))); // NOI18N
        getContentPane().add(skintaker);
        skintaker.setBounds(220, 140, 1030, 490);

        spine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/sh.png"))); // NOI18N
        getContentPane().add(spine);
        spine.setBounds(460, 20, 560, 590);

        housetype.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/HOUSE32.png"))); // NOI18N
        getContentPane().add(housetype);
        housetype.setBounds(450, 10, 900, 120);

        mansion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/mansion.png"))); // NOI18N
        getContentPane().add(mansion);
        mansion.setBounds(220, 170, 1010, 430);

        buthus.setBackground(new java.awt.Color(255, 51, 51));
        buthus.setFont(new java.awt.Font("Segoe UI Black", 0, 24));
        buthus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/housebut.png"))); // NOI18N
        buthus.setText("Select House");
        buthus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buthusMouseClicked(evt);
            }
        });
        getContentPane().add(buthus);
        buthus.setBounds(580, 600, 270, 89);

        mario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/mar.png"))); // NOI18N
        mario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marioMouseClicked(evt);
            }
        });
        getContentPane().add(mario);
        mario.setBounds(440, 0, 570, 190);

        no.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/noend2.png"))); // NOI18N
        getContentPane().add(no);
        no.setBounds(460, 20, 470, 150);

        night.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/nigggg.png"))); // NOI18N
        getContentPane().add(night);
        night.setBounds(470, 0, 490, 210);

        skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/skin.png"))); // NOI18N
        skin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skinMouseClicked(evt);
            }
        });
        getContentPane().add(skin);
        skin.setBounds(450, 20, 460, 180);

        slau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/slagg.png"))); // NOI18N
        getContentPane().add(slau);
        slau.setBounds(410, -150, 680, 450);

        pan1.setBackground(new java.awt.Color(0, 0, 0));
        pan1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(pan1);
        pan1.setBounds(400, 20, 560, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/Plague_Doctor_Chapel.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-100, -60, 1480, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backbutActionPerformed

private void buthusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buthusMouseClicked
panpan.setVisible(true);
slau.setVisible(false);
                spine.setVisible(false);
buthus.setVisible(false);
                housetype.setVisible(true);
                pan1.setVisible(false);
}//GEN-LAST:event_buthusMouseClicked

private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
panpan.setVisible(false);
housetype.setVisible(false);
spine.setVisible(false);
buthus.setVisible(false);
mario.setVisible(true);
pan1.setVisible(true);
jLabel3.setVisible(true);
marionette.setVisible(true);
backbut.setVisible(true);
}//GEN-LAST:event_jLabel3MouseClicked

private void marioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marioMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_marioMouseClicked

private void backbutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbutMouseClicked
housetype.setVisible(true);
panpan.setVisible(true);
marionette.setVisible(false);
mario.setVisible(false);
pan1.setVisible(false);
backbut.setVisible(false);
no.setVisible(false);
skintaker.setVisible(false);
noend.setVisible(false);
nightmarecove.setVisible(false);
mansion.setVisible(false);
skin.setVisible(false);
slau.setVisible(false);
night.setVisible(false);
}//GEN-LAST:event_backbutMouseClicked

private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
panpan.setVisible(false);
housetype.setVisible(false);
spine.setVisible(false);
buthus.setVisible(false);
mario.setVisible(false);
pan1.setVisible(true);
noend.setVisible(true);
backbut.setVisible(true);
no.setVisible(true);

}//GEN-LAST:event_jLabel4MouseClicked

private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
panpan.setVisible(false);
housetype.setVisible(false);
spine.setVisible(false);
buthus.setVisible(false);
mario.setVisible(false);
pan1.setVisible(true);
skintaker.setVisible(true);
backbut.setVisible(true);
skin.setVisible(true);
}//GEN-LAST:event_jLabel6MouseClicked

private void skinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skinMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_skinMouseClicked

private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
panpan.setVisible(false);
housetype.setVisible(false);
spine.setVisible(false);
buthus.setVisible(false);
mario.setVisible(false);
pan1.setVisible(true);
nightmarecove.setVisible(true);
backbut.setVisible(true);
night.setVisible(true);
}//GEN-LAST:event_jLabel5MouseClicked

private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
panpan.setVisible(false);
housetype.setVisible(false);
spine.setVisible(false);
buthus.setVisible(false);
mario.setVisible(false);
pan1.setVisible(true);
mansion.setVisible(true);
backbut.setVisible(true);
slau.setVisible(true);
}//GEN-LAST:event_jLabel7MouseClicked

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    int YesorNO =JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?","Exit",JOptionPane.YES_NO_OPTION);
    if(YesorNO==0){
        System.exit(0);
    }
    // TODO add your handling code here:
}//GEN-LAST:event_jButton9ActionPerformed

private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

}//GEN-LAST:event_backMouseClicked

private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    dispose();
    new Home().setVisible(true);
}//GEN-LAST:event_backActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Housetype().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton backbut;
    private javax.swing.JButton buthus;
    private javax.swing.JLabel housetype;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel mansion;
    private javax.swing.JLabel mario;
    private javax.swing.JLabel marionette;
    private javax.swing.JLabel night;
    private javax.swing.JLabel nightmarecove;
    private javax.swing.JLabel no;
    private javax.swing.JLabel noend;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel panpan;
    private javax.swing.JLabel skin;
    private javax.swing.JLabel skintaker;
    private javax.swing.JLabel slau;
    private javax.swing.JLabel spine;
    // End of variables declaration//GEN-END:variables
public void lol(){

    
}
}
