/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HOUSE1VIEW.java
 *
 * Created on Jan 1, 2002, 8:35:33 AM
 */

package loginform;

/**
 *
 * @author DFCAITTI
 */
public class HOUSE1VIEW extends javax.swing.JFrame {

    /** Creates new form HOUSE1VIEW */
    public HOUSE1VIEW() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/h1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 150, 920, 500);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/bgtohaoki.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOUSE1VIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
