/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LOADING_SCHED.java
 *
 * Created on Jan 1, 2009, 1:33:48 AM
 */

package loginform;

import javax.swing.JOptionPane;

/**
 *
 * @author DFCAITTI
 */
public class LOADING_SCHED extends javax.swing.JFrame implements Runnable {
    int s=0;
    Thread th;
    public LOADING_SCHED() {
         super("loading"); initComponents();
    setLocationRelativeTo(null); th=new Thread ((Runnable)this);
    }
public void setUploading(){
    setVisible(false);
    th.start();
}
public void run(){
    try{
        for(int i=2;i<200;i++){
            s=s+2;
                    int m=jProgressBar1.getMaximum();
                    int v=jProgressBar1.getValue();
                    if(v<m){
                        jProgressBar1.setValue(jProgressBar1.getValue()+1);
                    }else{
                        i=201;
                        setVisible(false);
                      new Reservation().setVisible(true);
                    }Thread.sleep(50);
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
}


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(498, 478));
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(0, 490, 146, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/LOWER.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 370, 430, 600);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/Rainy_scary.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 430, 330);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/bgto2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOADING_SCHED().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    public void takbo() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

}
