/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * studinfo.java
 *
 * Created on Nov 28, 2018, 9:52:20 PM
 */

package loginform;

/**
 *
 * @author DFCAITTI
 */
import javax.swing.*;
import java.awt.*;
public class studinfo extends javax.swing.JFrame {

    /** Creates new form studinfo */
    public studinfo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    
    
   
   
        
   
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(0, 51, 51));
        setMinimumSize(new java.awt.Dimension(790, 598));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 43));
        jLabel2.setText("X");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(750, 0, 45, 30);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 48));
        jButton1.setText("x");
        jPanel3.add(jButton1);
        jButton1.setBounds(730, 340, 60, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/dribbble_fps.gif"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 340, 790, 600);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, -340, 790, 950);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-790)/2, (screenSize.height-598)/2, 790, 598);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
