/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ticks.java
 *
 * Created on Jan 17, 2019, 12:58:23 PM
 */

package loginform;

import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author DFCAITTI
 */
public class Ticks extends javax.swing.JFrame {

    /** Creates new form Ticks */
    public Ticks() {
        initComponents();
    setLocationRelativeTo(null);
    wow();type.setSelectedIndex(-1);number.setSelectedIndex(-1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        type = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        number = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticket = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 444));
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/gen2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 480, 110);

        jButton2.setBackground(new java.awt.Color(237, 192, 147));
        jButton2.setFont(new java.awt.Font("Monospaced", 1, 20));
        jButton2.setText("Clear");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 320, 110, 50);

        jButton3.setBackground(new java.awt.Color(237, 192, 147));
        jButton3.setFont(new java.awt.Font("Monospaced", 1, 20));
        jButton3.setText("Print Ticket");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 380, 190, 50);

        jButton4.setBackground(new java.awt.Color(237, 192, 147));
        jButton4.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        jButton4.setText("Generate Ticket");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 320, 220, 50);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 10, true));
        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Narkisim", 1, 22));
        jLabel9.setForeground(new java.awt.Color(255, 51, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Price:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(350, 90, 70, 20);

        price.setBackground(new java.awt.Color(153, 153, 153));
        price.setFont(new java.awt.Font("Verdana", 1, 24));
        price.setForeground(new java.awt.Color(0, 51, 204));
        price.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        price.setEnabled(false);
        jPanel1.add(price);
        price.setBounds(340, 110, 90, 40);

        name1.setBackground(new java.awt.Color(153, 153, 153));
        name1.setFont(new java.awt.Font("Verdana", 1, 18));
        name1.setForeground(new java.awt.Color(0, 51, 204));
        name1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(name1);
        name1.setBounds(250, 40, 170, 30);

        jLabel10.setFont(new java.awt.Font("Narkisim", 1, 22));
        jLabel10.setForeground(new java.awt.Color(255, 51, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Name:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(290, 10, 80, 40);

        jLabel8.setFont(new java.awt.Font("Narkisim", 1, 22));
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Customer's ID:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 20, 160, 20);

        id.setBackground(new java.awt.Color(153, 153, 153));
        id.setFont(new java.awt.Font("Verdana", 1, 18));
        id.setForeground(new java.awt.Color(0, 51, 204));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(50, 40, 170, 30);

        type.setBackground(new java.awt.Color(102, 102, 102));
        type.setFont(new java.awt.Font("Verdana", 1, 18));
        type.setForeground(new java.awt.Color(255, 51, 0));
        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regular", "VIP\t" }));
        type.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeItemStateChanged(evt);
            }
        });
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type);
        type.setBounds(20, 110, 120, 40);

        jLabel6.setFont(new java.awt.Font("Narkisim", 1, 22));
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("House Type:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 90, 140, 20);

        number.setFont(new java.awt.Font("Verdana", 1, 18));
        number.setForeground(new java.awt.Color(255, 51, 0));
        number.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        number.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        number.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                numberItemStateChanged(evt);
            }
        });
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        number.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numberPropertyChange(evt);
            }
        });
        jPanel1.add(number);
        number.setBounds(180, 110, 140, 40);

        jLabel7.setFont(new java.awt.Font("Narkisim", 1, 22));
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("House Number:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 90, 170, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 130, 440, 180);

        jButton5.setBackground(new java.awt.Color(237, 192, 147));
        jButton5.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/backolit.png"))); // NOI18N
        jButton5.setText("Back");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/backknanam.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(330, 380, 130, 60);

        jLabel3.setBackground(new java.awt.Color(237, 192, 147));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform/giphy (19).gif"))); // NOI18N
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 470, 450);

        ticket.setBackground(new java.awt.Color(153, 153, 153));
        ticket.setColumns(20);
        ticket.setEditable(false);
        ticket.setFont(new java.awt.Font("Monospaced", 0, 22));
        ticket.setRows(5);
        jScrollPane1.setViewportView(ticket);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 0, 430, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String t = type.getSelectedItem().toString();
String h = number.getSelectedItem().toString();
String i = id.getText();
String n = name1.getText();
String p = price.getText();
if(t==null){
    JOptionPane.showMessageDialog(null, "House type is empty");
}
else if (i==null){
     JOptionPane.showMessageDialog(null, "ID is empty");
}else if(n==null){
       JOptionPane.showMessageDialog(null, "Name is empty");
}else if(h==null){
     JOptionPane.showMessageDialog(null, "House number is empty");
}
    

    ticket.setText("********************************\n");
ticket.setText(ticket.getText()+"**   Slaughter House ticket   **\n");
ticket.setText(ticket.getText()+"********************************\n");
Date obj = new Date();
String date = obj.toString();
ticket.setText(ticket.getText()+date+"\n");
ticket.setText(ticket.getText()+"House Type:"+type.getSelectedItem().toString()+"\n");
ticket.setText(ticket.getText()+"House number:"+number.getSelectedItem().toString()+"\n");
ticket.setText(ticket.getText()+"Customer's ID:"+id.getText()+"\n");
ticket.setText(ticket.getText()+"Customer's Name:"+name1.getText()+"\n");
ticket.setText(ticket.getText()+"Price :"+price.getText());







}//GEN-LAST:event_jButton4ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
price.setText(null);
number.setSelectedIndex(-1);
name1.setText(null);
jTextField3.setText(null);
id.setText(null);
type.setSelectedIndex(-1);
ticket.setText(null);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
    ticket.print();
}catch(Exception e){
    e.printStackTrace();
}
}//GEN-LAST:event_jButton3ActionPerformed

private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
char c=evt.getKeyChar();
if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
  getToolkit().beep();
    evt.consume();}
}//GEN-LAST:event_idKeyTyped

private void numberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_numberItemStateChanged
wow();
}//GEN-LAST:event_numberItemStateChanged

private void numberPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_numberPropertyChange
   wow();
}//GEN-LAST:event_numberPropertyChange

private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_numberActionPerformed

private void typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeItemStateChanged
if(type.getSelectedItem()=="Regular"){

    price.setText("1000");
}else if(type.getSelectedIndex()==-1) {
price.setText(null);
}

else {
    price.setText("2000");
}
}//GEN-LAST:event_typeItemStateChanged

private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
 wow();
}//GEN-LAST:event_typeActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
dispose();
new Home().setVisible(true);

}//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField name1;
    private javax.swing.JComboBox number;
    private javax.swing.JTextField price;
    private javax.swing.JTextArea ticket;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
private void wow(){
 

}
}


